DSND-1590 Set up boilerplate consumer code
companieshouse/officers-search-consumer pull request #1
Opened 2023-05-09 11:21 UTC by cgregoryCH

* Generated boilerplate consumer code using the consumer-maven-archetype.

[DSND-1590](https://companieshouse.atlassian.net/browse/DSND-1590)

2023-05-09 13:03 UTC, kinpang-CH submitted a review, later dismissed

2023-05-09 13:05 UTC, johncook-ch requested changes

2023-05-09 13:05 UTC, johncook-ch commented on pom.xml
> +        <spring.boot.version>2.7.10</spring.boot.version>
The latest Spring Boot version is now `2.7.11`. You can check the latest from this page https://start.spring.io/

2023-05-09 15:53 UTC, johncook-ch submitted a review, later dismissed

2023-05-10 08:28 UTC, johncook-ch approved these changes

2023-05-10 09:19 UTC, kinpang-CH approved these changes

2023-05-10 09:20 UTC, crowlandsCH approved these changes

2023-05-10 09:38 UTC, johncook-ch approved these changes

2023-05-10 09:41 UTC, merged