DSND-1594: Implement officers search consumer - upsert
companieshouse/officers-search-consumer pull request #3
Opened 2023-06-20 17:12 UTC by johncook-ch

* Refactored all Kafka-related classes to use `ResourceChangedData` as the payload type
* Added messaged routing for changed events
* Added API clients for Search API and Company Appointments API
[DSND-1594](https://companieshouse.atlassian.net/browse/DSND-1594)

2023-06-23 08:52 UTC, kinpang-CH commented on src/test/java/uk/gov/companieshouse/officerssearch/subdelta/SearchApiClientTest.java
> +//    @DisplayName("Should delegate to response handler when URIValidationException caught")
Commented out code?

2023-06-23 08:53 UTC, kinpang-CH requested changes
Is the commented out code left in on purpose?

2023-06-23 10:17 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/officerssearch/subdelta/SearchApiClientTest.java
> +//    @DisplayName("Should delegate to response handler when URIValidationException caught")
Gone

2023-06-23 10:18 UTC, johncook-ch commented
> Is the commented out code left in on purpose?

Nope. It was an act of negligence on my part :) It has now gone

2023-06-23 10:32 UTC, kinpang-CH submitted a review, later dismissed

2023-06-23 11:27 UTC, crowlandsCH approved these changes

2023-07-04 09:49 UTC, sthompsonCH approved these changes

2023-07-04 10:26 UTC, sthompsonCH approved these changes

2023-07-04 10:28 UTC, kinpang-CH approved these changes

2023-07-04 10:28 UTC, merged